{% set name = "django-multiselectfield" %}
{% set version = "0.1.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 437d72632f4c0ca416951917632529c3d1d42b62bb6c3c03e3396fa50265be94

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - django >=1.4
    - python >=3.4

test:
  imports:
    - multiselectfield
    - multiselectfield.db
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/goinnn/django-multiselectfield
  license: LGPL-3.0-only
  license_file: COPYING.LGPLv3
  summary: Django multiple select field

extra:
  recipe-maintainers:
    - JasmineDragon
