{% set name = "django-multiselectfield" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3f8b4fff3e07d4a91c8bb4b809bc35caeb22b41769b606f4c9edc53b8d72a667

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - django >=1.4
    - python >=3.4

test:
  imports:
    - multiselectfield
    - multiselectfield.db
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/goinnn/django-multiselectfield
  license: LGPL-3.0-only
  license_file: COPYING.LGPLv3
  summary: Django multiple select field

extra:
  recipe-maintainers:
    - JasmineDragon
